pipelines:
  demo_ci_pipeline:
    group: demo_group
    materials:
      demo_git: # name of material
        git: https://github.com/ThoughtWorksInc/ci-workshop-app.git
    stages:
      - commit: # name of stage
          clean_workspace: true
          jobs:
            build_and_test: # name of the job
              elastic_profile_id: demo-app
              tasks:
              - exec: # indicates type of task
                  command: bash
                  arguments:
                  - -c
                  - docker build . -t davified/ci-workshop-app:v${GO_PIPELINE_LABEL} --target Base
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker run davified/ci-workshop-app:v${GO_PIPELINE_LABEL} bin/test.sh
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker build . -t davified/ci-workshop-app:v${GO_PIPELINE_LABEL} --target Build
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker run davified/ci-workshop-app:v${GO_PIPELINE_LABEL} bin/test_model_metrics.sh
              artifacts:
              - external:
                  id: docker-release-candidate
                  store_id: dockerhub # artifact store id (configured on gocd UI)
                  configuration:
                    options:
                      Image: davified/ci-workshop-app
                      Tag: v${GO_PIPELINE_LABEL}
      - deploy_staging:
          clean_workspace: true
          jobs:
            deploy_staging:
              elastic_profile_id: docker-dind-kubectl
              tasks:
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - kubectl set image deployment/ml-cd-starter-kit-ci-workshop-app-chart ci-workshop-app-chart=davified/ci-workshop-app:v${GO_PIPELINE_LABEL} # ci-workshop-app-chart is the name of the chart in ml-cd-starter-kit
      - deploy_prod:
          clean_workspace: true
          approval:
            type: manual
          jobs:
            deploy_staging:
              elastic_profile_id: docker-dind-kubectl
              tasks:
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - kubectl set image deployment/ml-cd-starter-kit-ci-workshop-app-chart ci-workshop-app-chart=davified/ci-workshop-app:v${GO_PIPELINE_LABEL} # ci-workshop-app-chart is the name of the chart in ml-cd-starter-kit
