# simple.gocd.yaml
pipelines:
  pipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ThoughtWorksInc/ci-workshop-app.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              elastic_profile_id: demo-app
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - echo "hello world"