# simple.gocd.yaml
pipelines:
  demo_ci_pipeline:
    group: demo_group
    materials:
      demo_git:  # this is the name of material
        git: https://github.com/ThoughtWorksInc/ci-workshop-app.git
    stages:
      - commit: # name of stage
          clean_workspace: true
          jobs:
            build_and_test: # name of the job
              elastic_profile_id: demo-app
              tasks:
              - exec: # indicates type of task
                  command: bash
                  arguments:
                  - -c
                  - docker build . -t davified/ci-workshop-app:latest --target Base
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker run davified/ci-workshop-app:latest bin/test.sh
              - exec:
                  command: bash
                  - -c
                  - docker build . -t davified/ci-workshop-app:latest --target Build
              - exec:
                  command: bash
                  - -c
                  - docker run davified/ci-workshop-app:latest bin/test_model_metrics.sh
              artifacts:  # artifacts#build
              - external:
                  id: docker-release-candidate
                  store_id: dockerhub # artifact store id (configured on gocd)
                  configuration:
                    options:
                      Image: davified/ci-workshop-app
                      Tag: latest # v${GO_PIPELINE_LABEL}
                    secure_options:
                      some_secure_property: ""
      - deploy_staging:
          clean_workspace: true
          jobs:
            deploy_staging:
              elastic_profile_id: demo-app
              tasks:
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - apt-get install -y kubectl
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - kubectl set image deployment/ml-cd-starter-kit-ci-workshop-app-chart ci-workshop-app=davified/ci-workshop-app:latest


# # deploy-to-staging
# docker run my_image:build bin/deploy_kubernetes_staging.sh

# # deploy-to-prod
# docker run my_image:build bin/deploy_kubernetes_prod.sh


# questions:
# - how to cache docker image locally so that we don't have to build from scratch in the first stage everytime?
# - how to configure external artifact store (dockerhub) using yaml? i.e. how to automate the instructions here https://docs.gocd.org/current/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_build_pipeline.html
# - storing secure variables: https://api.gocd.org/current/#encryption
# references 
# - https://pnguyen.io/posts/a-sample-gocd-pipeline and https://github.com/hpcsc/sample-pipeline-backend
