# simple.gocd.yaml
pipelines:
  demo_ci_pipeline:
    group: demo_group
    materials:
      demo_git:  # this is the name of material
        git: https://github.com/ThoughtWorksInc/ci-workshop-app.git
      # docker_artifact:
      #   pipeline: demo_ci_pipeline
      #   stage: commit
    stages:
      - commit: # name of stage
          clean_workspace: true
          jobs:
            build_and_test: # name of the job
              elastic_profile_id: demo-app
              tasks:
              - exec: # indicates type of task
                  command: bash
                  arguments:
                  - -c
                  - docker build . -t davified/ci-workshop-app:latest --target Base
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker run davified/ci-workshop-app:latest bin/test.sh
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker build . -t davified/ci-workshop-app:latest --target Build
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - docker run davified/ci-workshop-app:latest bin/test_model_metrics.sh
              artifacts:  # artifacts#build
              - external:
                  id: docker-release-candidate
                  store_id: dockerhub # artifact store id (configured on gocd)
                  configuration:
                    options:
                      Image: davified/ci-workshop-app
                      Tag: latest # v${GO_PIPELINE_LABEL}
                    secure_options:
                      some_secure_property: ""
      - deploy_staging:
          clean_workspace: true
          jobs:
            deploy_staging:
              elastic_profile_id: docker-dind-kubectl
              tasks:
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - kubectl set image deployment/ml-cd-starter-kit-ci-workshop-app-chart ci-workshop-app=davified/ci-workshop-app:latest
