# simple.gocd.yaml
pipelines:
  demo_ci_pipeline:
    group: demo_group
    materials:
      demo_git:  # this is the name of material
        git: https://github.com/ThoughtWorksInc/ci-workshop-app.git
    stages:
      - build: # name of stage
          clean_workspace: true
          jobs:
            build: # name of the job
              elastic_profile_id: demo-app
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                   - -c
                   - echo "hello world"