apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-template-deployment
  labels:
    app: ml-app-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app-template
  template:
    metadata:
      labels:
        app: ml-app-template
    spec:
      containers:
      - name: ml-app-template
        image: asia.gcr.io/ai-sg-workshop/ml-app-template
        command: ["bin/start_server.sh"]