apiVersion: v1
kind: Service
metadata:
  name: ml-app-template-service
  labels:
    run: ml-app-template
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ml-app-template